#!/bin/sh

set -euo pipefail

# for backwards compatibility, separates host and port from url
export BACKOFFICE_SERVICE_DOMAIN=${BACKOFFICE_SERVICE_DOMAIN:-${BACKOFFICE_SERVICE_HOST%:*}}
export BACKOFFICE_SERVICE_PORT=${BACKOFFICE_SERVICE_PORT:-${BACKOFFICE_SERVICE_HOST##*:}}

export IDENTITY_SERVICE_DOMAIN=${IDENTITY_SERVICE_DOMAIN:-${IDENTITY_SERVICE_HOST%:*}}
export IDENTITY_SERVICE_PORT=${IDENTITY_SERVICE_PORT:-${IDENTITY_SERVICE_HOST##*:}}

export META_SERVICE_DOMAIN=${META_SERVICE_DOMAIN:-${META_SERVICE_HOST%:*}}
export META_SERVICE_PORT=${META_SERVICE_PORT:-${META_SERVICE_HOST##*:}}

export CRASH_ORACLE_BASE_DOMAIN=${CRASH_ORACLE_BASE_DOMAIN:-${CRASH_ORACLE_BASE_HOST%:*}}
export CRASH_ORACLE_BASE_PORT=${CRASH_ORACLE_BASE_PORT:-${CRASH_ORACLE_BASE_HOST##*:}}

export CRASH_ORACLE_BSC_DOMAIN=${CRASH_ORACLE_BSC_DOMAIN:-${CRASH_ORACLE_BSC_HOST%:*}}
export CRASH_ORACLE_BSC_PORT=${CRASH_ORACLE_BSC_PORT:-${CRASH_ORACLE_BSC_HOST##*:}}

export CRASH_ORACLE_PULSECHAIN_DOMAIN=${CRASH_ORACLE_PULSECHAIN_DOMAIN:-${CRASH_ORACLE_PULSECHAIN_HOST%:*}}
export CRASH_ORACLE_PULSECHAIN_PORT=${CRASH_ORACLE_PULSECHAIN_PORT:-${CRASH_ORACLE_PULSECHAIN_HOST##*:}}

# strip https:// or https:// from domain if necessary
BACKOFFICE_SERVICE_DOMAIN=${BACKOFFICE_SERVICE_DOMAIN##*://}
IDENTITY_SERVICE_DOMAIN=${IDENTITY_SERVICE_DOMAIN##*://}
META_SERVICE_DOMAIN=${META_SERVICE_DOMAIN##*://}
CRASH_ORACLE_BASE_DOMAIN=${CRASH_ORACLE_BASE_DOMAIN##*://}
CRASH_ORACLE_BSC_DOMAIN=${CRASH_ORACLE_BSC_DOMAIN##*://}
CRASH_ORACLE_PULSECHAIN_DOMAIN=${CRASH_ORACLE_PULSECHAIN_DOMAIN##*://}

echo using backoffice-service: ${BACKOFFICE_SERVICE_DOMAIN} with port: ${BACKOFFICE_SERVICE_PORT}
echo using identity-service: ${IDENTITY_SERVICE_DOMAIN} with port: ${IDENTITY_SERVICE_PORT}
echo using meta-service: ${META_SERVICE_DOMAIN} with port: ${META_SERVICE_PORT}
echo using crash-oracle-base: ${CRASH_ORACLE_BASE_DOMAIN} with port: ${CRASH_ORACLE_BASE_PORT}
echo using crash-oracle-bsc: ${CRASH_ORACLE_BSC_DOMAIN} with port: ${CRASH_ORACLE_BSC_PORT}
echo using crash-oracle-pulsechain: ${CRASH_ORACLE_PULSECHAIN_DOMAIN} with port: ${CRASH_ORACLE_PULSECHAIN_PORT}

exec caddy run --config Caddyfile --adapter caddyfile 2>&1
